import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * BootifyJS Documentation Sidebar Configuration
 * 
 * This defines the complete navigation structure for the BootifyJS documentation site.
 * Organized into three main sidebars: Docs, API Reference, and Templates.
 * 
 * NOTE: Currently using autogenerated mode for existing tutorial content.
 * Once documentation files are created in subsequent tasks, uncomment the manual
 * sidebar configuration below and remove the autogenerated configuration.
 */
const sidebars: SidebarsConfig = {
  // Temporary: Using autogenerated sidebar for existing tutorial content
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Placeholder sidebars for API and Templates (will be populated in future tasks)
  apiSidebar: [{ type: 'autogenerated', dirName: '.' }],
  templatesSidebar: [{ type: 'autogenerated', dirName: '.' }],

  /* 
   * COMPLETE SIDEBAR STRUCTURE (to be activated once documentation files are created)
   * 
   * Uncomment this section and remove the autogenerated configuration above
   * once the documentation files from tasks 3-21 are created.
   */

  /*
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/project-structure',
        'getting-started/first-application',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'core-concepts/overview',
        'core-concepts/dependency-injection',
        'core-concepts/decorators',
        'core-concepts/lifecycle',
        'core-concepts/request-context',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Core',
          items: [
            'modules/core/overview',
            'modules/core/controllers',
            'modules/core/services',
            'modules/core/routing',
            'modules/core/validation',
          ],
        },
        {
          type: 'category',
          label: 'Events',
          items: [
            'modules/events/overview',
            'modules/events/event-bus',
            'modules/events/handlers',
            'modules/events/buffered-events',
          ],
        },
        {
          type: 'category',
          label: 'Cache',
          items: [
            'modules/cache/overview',
            'modules/cache/decorators',
            'modules/cache/stores',
            'modules/cache/custom-stores',
          ],
        },
        {
          type: 'category',
          label: 'Logging',
          items: [
            'modules/logging/overview',
            'modules/logging/basic-usage',
            'modules/logging/context-logging',
            'modules/logging/transports',
          ],
        },
        {
          type: 'category',
          label: 'Auth',
          items: [
            'modules/auth/overview',
            'modules/auth/jwt-strategy',
            'modules/auth/api-key-strategy',
            'modules/auth/custom-strategies',
          ],
        },
        {
          type: 'category',
          label: 'Config',
          items: [
            'modules/config/overview',
            'modules/config/schema-validation',
            'modules/config/environment-variables',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/custom-middleware',
        'advanced/error-handling',
        'advanced/testing-strategies',
        'advanced/performance',
        'advanced/security',
        'advanced/deployment',
        'advanced/extending-framework',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/comparison',
        'guides/migration-from-express',
        'guides/migration-from-nestjs',
        'guides/best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/documentation',
        'contributing/style-guide',
      ],
    },
  ],

  // API Reference sidebar
  apiSidebar: [
    {
      type: 'doc',
      id: 'api-reference/decorators',
      label: 'Decorators',
    },
    {
      type: 'doc',
      id: 'api-reference/core-api',
      label: 'Core API',
    },
    {
      type: 'doc',
      id: 'api-reference/events-api',
      label: 'Events API',
    },
    {
      type: 'doc',
      id: 'api-reference/cache-api',
      label: 'Cache API',
    },
    {
      type: 'doc',
      id: 'api-reference/logging-api',
      label: 'Logging API',
    },
    {
      type: 'doc',
      id: 'api-reference/auth-api',
      label: 'Auth API',
    },
    {
      type: 'doc',
      id: 'api-reference/config-api',
      label: 'Config API',
    },
  ],

  // Templates sidebar
  templatesSidebar: [
    {
      type: 'doc',
      id: 'templates/rest-api',
      label: 'REST API',
    },
    {
      type: 'doc',
      id: 'templates/authentication',
      label: 'Authentication',
    },
    {
      type: 'doc',
      id: 'templates/crud-operations',
      label: 'CRUD Operations',
    },
    {
      type: 'doc',
      id: 'templates/event-driven',
      label: 'Event-Driven',
    },
    {
      type: 'doc',
      id: 'templates/caching-patterns',
      label: 'Caching Patterns',
    },
    {
      type: 'doc',
      id: 'templates/error-handling',
      label: 'Error Handling',
    },
    {
      type: 'doc',
      id: 'templates/middleware',
      label: 'Middleware',
    },
    {
      type: 'doc',
      id: 'templates/testing',
      label: 'Testing',
    },
    {
      type: 'doc',
      id: 'templates/database-integration',
      label: 'Database Integration',
    },
    {
      type: 'doc',
      id: 'templates/full-application',
      label: 'Full Application',
    },
  ],
  */
};

export default sidebars;
